jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test building with EESSI
      run: |
        module load HDF5 CMake buildenv
        mkdir build
        cd build/
        cmake ..
        make -j
        ctest --output-on-failure --verbose
      shell: bash
